name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - '.idea/copyright/*.xml'
      - '.github/workflows/pullrequest.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Info
        id: release-info
        uses: GeyserMC/actions/previous-release@master
        with:
          data: ${{ vars.RELEASEACTION_PREVRELEASE }}

      - name: Checkout repository and submodules
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Floodgate
        run: ./gradlew build
        env:
          BUILD_NUMBER: ${{ steps.release-info.outputs.curentRelease }}

      - name: Archive artifacts (Floodgate Bungee)
        uses: actions/upload-artifact@v7
        if: success()
        with:
          path: bungee/build/libs/floodgate-bungee.jar
          archive: false
          if-no-files-found: error

      - name: Archive artifacts (Floodgate Spigot)
        uses: actions/upload-artifact@v7
        if: success()
        with:
          path: spigot/build/libs/floodgate-spigot.jar
          archive: false
          if-no-files-found: error

      - name: Archive artifacts (Floodgate Velocity)
        uses: actions/upload-artifact@v7
        if: success()
        with:
          path: velocity/build/libs/floodgate-velocity.jar
          archive: false
          if-no-files-found: error

      - name: Archive artifacts (Floodgate Mongo Database)
        uses: actions/upload-artifact@v7
        if: success()
        with:
          path: database/mongo/build/libs/floodgate-mongo-database.jar
          archive: false
          if-no-files-found: error

      - name: Archive artifacts (Floodgate MySQL Database)
        uses: actions/upload-artifact@v7
        if: success()
        with:
          path: database/mysql/build/libs/floodgate-mysql-database.jar
          archive: false
          if-no-files-found: error

      - name: Archive artifacts (Floodgate Sqlite Database)
        uses: actions/upload-artifact@v7
        if: success()
        with:
          path: database/sqlite/build/libs/floodgate-sqlite-database.jar
          archive: false
          if-no-files-found: error
