name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - '.gitignore'
      - '.idea/copyright/*.xml'
      - '.github/workflows/pullrequest.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Info
        id: release-info
        uses: GeyserMC/actions/previous-release@master
        with:
          data: ${{ vars.RELEASEACTION_PREVRELEASE }}

      - name: Checkout repository and submodules
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Floodgate
        run: ./gradlew build
        env:
          BUILD_NUMBER: ${{ steps.release-info.outputs.curentRelease }}

      - name: Archive Artifacts
        uses: GeyserMC/actions/upload-multi-artifact@master
        if: success()
        with:
          artifacts: |
            bungee/build/libs/floodgate-bungee.jar
            spigot/build/libs/floodgate-spigot.jar
            velocity/build/libs/floodgate-velocity.jar
            database/mongo/build/libs/floodgate-mongo-database.jar
            database/mysql/build/libs/floodgate-mysql-database.jar
            database/sqlite/build/libs/floodgate-sqlite-database.jar

